import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#c9c6c5",
        "primary-fixed": "#e5e2e1",
        "secondary": "#5e5e5e",
        "on-tertiary-fixed-variant": "#464747",
        "on-primary": "#ffffff",
        "on-secondary-container": "#646464",
        "primary-container": "#1c1b1b",
        "on-background": "#1a1c1b",
        "inverse-primary": "#c9c6c5",
        "on-surface": "#1a1c1b",
        "warning": "#D97706",
        "outline": "#747878",
        "surface-variant": "#e3e2e0",
        "secondary-container": "#e3e2e2",
        "inverse-surface": "#2f3130",
        "wallet-locked": "#991B1B",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e3e2e0",
        "surface-tint": "#5f5e5e",
        "tertiary": "#000000",
        "outline-variant": "#c4c7c7",
        "background": "#faf9f7",
        "primary": "#000000",
        "on-primary-container": "#858383",
        "surface": "#faf9f7",
        "tertiary-container": "#1a1c1c",
        "background-light": "#F9F8F6",
        "error-container": "#ffdad6",
        "surface-container": "#efeeec",
        "on-secondary": "#ffffff",
        "surface-dim": "#dadad8",
        "surface-bright": "#faf9f7",
        "session-orange": "#EA580C",
        "secondary-fixed-dim": "#c7c6c6",
        "pending": "#2563EB",
        "on-tertiary-container": "#838484",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-high": "#e9e8e6",
        "success": "#16A34A",
        "secondary-fixed": "#e3e2e2",
        "captcha-amber": "#F59E0B",
        "on-surface-variant": "#444748",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-container-low": "#f4f3f1",
        "error": "#DC2626",
        "on-secondary-fixed-variant": "#464747",
        "on-primary-fixed": "#1c1b1b",
        "background-dark": "#0A0A0A",
        "on-tertiary": "#ffffff",
        "wallet-unlocked": "#166534",
        "on-primary-fixed-variant": "#474646",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#c7c6c6",
        "inverse-on-surface": "#f1f1ef",
        "tertiary-fixed": "#e3e2e2"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        sm: "8px",
        md: "16px",
        xxl: "48px",
        "drawer-width": "420px",
        "sidebar-collapsed": "72px",
        xs: "4px",
        lg: "24px",
        xl: "40px",
        "sidebar-expanded": "260px"
      },
      fontFamily: {
        "page-title": ["Inter", "sans-serif"],
        "technical-data": ["JetBrains Mono", "monospace"],
        "section-title": ["Inter", "sans-serif"],
        "status": ["Inter", "sans-serif"],
        "button-label": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        "card-title": ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"]
      },
      fontSize: {
        "page-title": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "technical-data": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "section-title": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        status: ["11px", { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "600" }],
        "button-label": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        body: ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "card-title": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
};

export default config;
