// Auto-generated by contracts/deploy.ts after deployment
// Until you deploy, the mock anchor in registry-client.ts handles everything
export const DEPLOYMENTS = {
  "base-sepolia": {
    PraxisPaymentRegistry: "",   // filled by deploy.ts
    chainId: 84532,
    deployedAt: "",
    deployer: "",
  },
  "localhost": {
    PraxisPaymentRegistry: "",   // filled by deploy.ts
    chainId: 31337,
    deployedAt: "",
    deployer: "",
  },
} as const;
