import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying with account:", deployer.address);
  console.log("Balance:", ethers.formatEther(await ethers.provider.getBalance(deployer.address)), "ETH");

  // Deploy PraxisPaymentRegistry
  const Registry = await ethers.getContractFactory("PraxisPaymentRegistry");
  const registry = await Registry.deploy();
  await registry.waitForDeployment();

  const registryAddress = await registry.getAddress();
  console.log("\n✅ PraxisPaymentRegistry deployed to:", registryAddress);

  // Save deployment address to src/blockchain/deployments.ts
  const deploymentsPath = path.join(__dirname, "../src/blockchain/deployments.ts");
  const content = `// Auto-generated by contracts/deploy.ts — do not edit manually
export const DEPLOYMENTS = {
  "base-sepolia": {
    PraxisPaymentRegistry: "${registryAddress}",
    chainId: 84532,
    deployedAt: "${new Date().toISOString()}",
    deployer: "${deployer.address}",
  },
  "localhost": {
    PraxisPaymentRegistry: "",
    chainId: 31337,
    deployedAt: "",
    deployer: "",
  },
} as const;
`;

  fs.writeFileSync(deploymentsPath, content);
  console.log("📄 Deployment address saved to src/blockchain/deployments.ts");
  console.log("\nAdd to your .env:");
  console.log(`PRAXIS_REGISTRY_ADDRESS=${registryAddress}`);
  console.log("CHAIN_MODE=base-sepolia");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
